version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=2172/fomo
      - MYSQL_DATABASE=ppro
  email:
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
