server:
  error:
    include-message: always
    include-binding-errors: always


spring:
  datasource:
    password: 2172/fomo
    url: jdbc:mysql://localhost:3306/ppro
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true
  session:
    store-type: jdbc
    jdbc:
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      initialize-schema: embedded
      table-name: SPRING_SESSION
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 75MB
  mvc:
    hidden-method:
      filter:
        enabled: true

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
logging:
  level:
    org:
      springframework:
        security: DEBUG